name: web-app ci

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: Pragati1109
          POSTGRES_DB: health_check
        ports:
          - 5432:5432
    steps:
      - run: npm test
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USERNAME: postgres
          DB_PASSWORD: Pragati1109
          DB_NAME: health_check