name: webapp-ci

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.9.0'
      
      - name: Install PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib

      - name: Start PostgreSQL service
        run: |
          sudo service postgresql start
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${{ secrets.DB_PASSWORD }}';"
          sudo -u postgres psql -c "CREATE DATABASE ${{ secrets.DB_NAME }};"

      - name: Install dependencies
        run: npm install

      - name: Start Server in Background
        run: nohup node index.js > server.log 2>&1 &
        env:
          DB_HOST: "${{ secrets.DB_HOST }}"
          DB_USER: "${{ secrets.DB_USER }}"
          DB_PASS: "${{ secrets.DB_PASSWORD }}"
          DB_DBNAME: "${{ secrets.DB_NAME }}"
          DB_DIALECT: "postgres"

      - name: Starting server
        run: node index.js
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          DB_DBNAME: ${{ secrets.DB_NAME }}
          DB_DIALECT: "postgres"

      - name: Setting up PostgreSQL
        run: |
          echo "Setting up PostgreSQL environment variables..."
          echo "DB_USER = ${{ secrets.DB_USER }}"
          echo "DB_HOST = ${{ secrets.DB_HOST }}"
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          echo "DB_DBNAME = ${{ secrets.DB_NAME }}"
          echo "DB_DIALECT = postgres"
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          DB_DBNAME: ${{ secrets.DB_NAME }}
          DB_DIALECT: "postgres"

      - name: Stop Server
        run: pkill -f "node index.js"

      - name: Run tests
        run: npm test
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASSWORD }}
          DB_DBNAME: ${{ secrets.DB_NAME }}
          DB_DIALECT: "postgres"