name: webapp-ci

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: "Run Tests - 1"
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - run: npm ci

      - run: npm test
        env:
          DB_USERNAME: ${{secrets.POSTGRES_USER}}
          DB_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          DB_NAME: ${{secrets.POSTGRES_DB}}
          DB_HOST: "localhost"
          DB_PORT: "5432"
